{{-  range .Values.env.secrets.postgres.databases }}
apiVersion: v1
kind: Secret
metadata:
    name: postgres-cluster-{{ .name }}
    labels:
      cnpg.io/reload: "true"
type:  kubernetes.io/basic-auth
stringData:
    username: {{ .name | quote }}
    password: {{ .password | quote }}
---
{{- end }}