{{- if and .Values.proxy .Values.proxy.applications }}
{{- range .Values.proxy.applications }}
{{- if .exposed }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: networking
      sectionName: websecure
  hostnames:
    - "{{ .name }}.{{ $.Values.env.domain }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .name }}
          port: 80
---
{{- end }}
{{- end }}
{{- end }}