apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: application
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: networking
      sectionName: websecure
  hostnames:
    - "app.{{ .Values.env.domain }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: application
          port: 80